// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALS2nNG76SvCFeuYQ8Km76TDMDYMY92iE',
    appId: '1:892688355669:web:9f17a416a111dfc74b5fdc',
    messagingSenderId: '892688355669',
    projectId: 'pawdetect-flutter',
    authDomain: 'pawdetect-flutter.firebaseapp.com',
    storageBucket: 'pawdetect-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIkcdxNaRh1W3vvLBy5FGwM0DbA0C3K0',
    appId: '1:892688355669:android:b323544565279e164b5fdc',
    messagingSenderId: '892688355669',
    projectId: 'pawdetect-flutter',
    storageBucket: 'pawdetect-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQ3KLEKk04WXN7ARNFvBokbtyg-Q3EO4',
    appId: '1:892688355669:ios:26563222a659ff444b5fdc',
    messagingSenderId: '892688355669',
    projectId: 'pawdetect-flutter',
    storageBucket: 'pawdetect-flutter.firebasestorage.app',
    iosBundleId: 'com.example.pawdetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQ3KLEKk04WXN7ARNFvBokbtyg-Q3EO4',
    appId: '1:892688355669:ios:26563222a659ff444b5fdc',
    messagingSenderId: '892688355669',
    projectId: 'pawdetect-flutter',
    storageBucket: 'pawdetect-flutter.firebasestorage.app',
    iosBundleId: 'com.example.pawdetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALS2nNG76SvCFeuYQ8Km76TDMDYMY92iE',
    appId: '1:892688355669:web:b27eee00aa5f91754b5fdc',
    messagingSenderId: '892688355669',
    projectId: 'pawdetect-flutter',
    authDomain: 'pawdetect-flutter.firebaseapp.com',
    storageBucket: 'pawdetect-flutter.firebasestorage.app',
  );
}
