@startuml
title Unauthenticated user
actor Guest

rectangle {
  usecase "Submit found pet report" as UC1
  usecase "Browse pet reports" as UC2
  usecase "Filter reports" as UC3
  
}

rectangle {
  usecase "View report details" as UC4
  usecase "Register new account" as UC5
  usecase "Switch language" as UC6
  
}

Guest -up-> UC1
Guest -up-> UC2
Guest -up-> UC3
Guest -down-> UC4
Guest -down-> UC5
Guest -down-> UC6
@enduml
